"""
Report Generator - Creates Markdown reports with annotated charts.
"""

import logging
from datetime import datetime
from pathlib import Path
from typing import Optional

from src.models import Signal, SignalType, PatternType
from src.visual.annotator import ChartAnnotator, get_annotator

logger = logging.getLogger(__name__)

# Report template
REPORT_TEMPLATE = """# Trading Signal Report: {symbol}

> Generated: {timestamp}

---

## 📊 Signal Summary

| Field | Value |
|-------|-------|
| **Symbol** | {symbol} |
| **Signal Type** | {signal_badge} |
| **Pattern** | {pattern} |
| **Confidence** | {confidence:.0%} |
| **Trend** | {trend} |

---

## 📈 Technical Levels

| Level | Price |
|-------|-------|
| **Support** | {support} |
| **Resistance** | {resistance} |
| **Fibonacci** | {fibonacci} |

---

## 🧠 AI Analysis

{analysis_summary}

---

## 📸 Annotated Chart

![Chart Analysis]({chart_image})

---

## ⚠️ Disclaimer

This report is generated by an AI system for informational purposes only. 
It does not constitute financial advice. Always do your own research.

---

*Report ID: {report_id}*
"""


class ReportGenerator:
    """Generates Markdown reports for trading signals."""
    
    def __init__(
        self,
        output_dir: Path = None,
        annotator: ChartAnnotator = None,
    ):
        """Initialize report generator.
        
        Args:
            output_dir: Directory to save reports
            annotator: ChartAnnotator instance
        """
        self.output_dir = output_dir or Path("data/reports")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.annotator = annotator or get_annotator()
    
    def generate(
        self,
        signal: Signal,
        chart_image_path: Optional[str] = None,
        annotate: bool = True,
    ) -> Path:
        """Generate a report for a signal.
        
        Args:
            signal: Signal with analysis results
            chart_image_path: Path to chart image
            annotate: Whether to annotate the image
            
        Returns:
            Path to generated report
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_id = f"{signal.symbol}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        # Annotate chart if available
        annotated_image = None
        if chart_image_path and Path(chart_image_path).exists():
            if annotate:
                annotated_path = self.output_dir / f"{report_id}_chart.png"
                
                # Extract pattern_box from notes if available
                pattern_box = None
                if signal.notes:
                    try:
                        import json
                        notes_data = json.loads(signal.notes)
                        pattern_box = notes_data.get("pattern_box")
                        if pattern_box:
                            pattern_box = tuple(pattern_box)
                            logger.info(f"Pattern box found: {pattern_box}")
                    except (json.JSONDecodeError, TypeError):
                        pass
                
                annotated_image = self.annotator.annotate(
                    image_path=chart_image_path,
                    output_path=annotated_path,
                    support_level=signal.support_level,
                    resistance_level=signal.resistance_level,
                    pattern_box=pattern_box,
                    pattern_name=signal.pattern_detected if signal.pattern_detected != PatternType.NONE else None,
                    trend=signal.trend,
                    signal_type=signal.signal_type,
                    analysis_summary=signal.analysis_summary,
                )
            else:
                annotated_image = Path(chart_image_path)
        
        # Generate signal badge
        signal_badge = self._get_signal_badge(signal.signal_type)
        
        # Format report
        report_content = REPORT_TEMPLATE.format(
            symbol=signal.symbol,
            timestamp=timestamp,
            signal_badge=signal_badge,
            pattern=signal.pattern_detected.replace("_", " ").title() if signal.pattern_detected else "None",
            confidence=signal.pattern_confidence,
            trend=signal.trend.upper() if signal.trend else "Unknown",
            support=f"${signal.support_level:.2f}" if signal.support_level else "N/A",
            resistance=f"${signal.resistance_level:.2f}" if signal.resistance_level else "N/A",
            fibonacci=signal.fibonacci_level or "N/A",
            analysis_summary=signal.analysis_summary or "No analysis available.",
            chart_image=annotated_image.name if annotated_image else "No chart available",
            report_id=report_id,
        )
        
        # Save report
        report_path = self.output_dir / f"{report_id}.md"
        report_path.write_text(report_content, encoding="utf-8")
        
        logger.info(f"Generated report: {report_path}")
        
        # Update signal with paths
        signal.report_path = str(report_path)
        if annotated_image:
            signal.chart_image_path = str(annotated_image)
        
        return report_path
    
    def _get_signal_badge(self, signal_type: SignalType) -> str:
        """Get emoji badge for signal type."""
        badges = {
            SignalType.CANDIDATE: "✅ **CANDIDATE**",
            SignalType.NOT_CANDIDATE: "❌ **NOT CANDIDATE**",
            SignalType.PENDING: "⏳ **PENDING REVIEW**",
        }
        return badges.get(signal_type, "❓ Unknown")


def get_report_generator(output_dir: Path = None) -> ReportGenerator:
    """Get ReportGenerator instance."""
    return ReportGenerator(output_dir=output_dir)
